export const BUY_FRUIT = "BUY_FRUIT";
export const BUY_VEGETABLE = "BUY_VEGETABLE";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const FETCH_RANDOM_USER_REQUEST = "FETCH_RANDOM_USER_REQUEST";
export const FETCH_RANDOM_USER_SUCCESS = "FETCH_RANDOM_USER_SUCCESS";
export const FETCH_RANDOM_USER_FAILURE = "FETCH_RANDOM_USER_FAILURE";

export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const DECREMENT_PAGE = "DECREMENT_PAGE";